create table employee(
    id BIGINT generated by default as identity,
    first_name VARCHAR(256),
    last_name VARCHAR(256),
);

create table tweet(
    id BIGINT generated by default as identity,
    entry VARCHAR(256),
    hashtag VARCHAR(50),
    employee_id BIGINT,
    last_modified_at timestamp DEFAULT CURRENT_TIMESTAMP,
    foreign key(employee_id) references employee(id)
);

create table follower(
    id  BIGINT generated by default as identity,
    employee_id BIGINT,
    follower_id BIGINT,
    foreign key(employee_id) references employee(id),
    foreign key(follower_id) references employee(id)
)